/**
 * Text Detection Library Implementation
 */

#include "text_detector.h"
#include "bounding_boxes.h"
#include <stdlib.h>
#include <string.h>

/* Model entry function - generated by onnx2c */
extern void entry(const float tensor_input[1][3][TEXT_DETECTOR_INPUT_HEIGHT][TEXT_DETECTOR_INPUT_WIDTH],
                  float tensor_output[1][1][TEXT_DETECTOR_OUTPUT_HEIGHT][TEXT_DETECTOR_OUTPUT_WIDTH]);

/* Image I/O functions from image_io.c */
extern int load_png(const char* filename, float rgb[TEXT_DETECTOR_INPUT_HEIGHT][TEXT_DETECTOR_INPUT_WIDTH][3]);
extern int save_annotated_image(const char* filename, const char* original_image,
                                const BoundingBoxList* boxes);

/* OCR internal functions from ocr.c */
extern int ocr_init(const char* tessdata_path, const char* language);
extern void ocr_cleanup(void);

/* Library state */
static int initialized = 0;

/**
 * Internal definition of text_detector_result_t.
 * This is opaque in the public header to prevent direct access.
 */
struct text_detector_result_t {
    float output[1][1][TEXT_DETECTOR_OUTPUT_HEIGHT][TEXT_DETECTOR_OUTPUT_WIDTH];
    text_detector_boxes_t boxes;
};

int text_detector_init(const char* tessdata_path, const char* language) {
    if (initialized) {
        return 0;  /* Already initialized */
    }

    /* Initialize OCR first */
    if (ocr_init(tessdata_path, language) != 0) {
        return -1;
    }

    initialized = 1;
    return 0;
}

void text_detector_cleanup(void) {
    if (initialized) {
        ocr_cleanup();
    }
    initialized = 0;
}

text_detector_result_t* text_detector_result_create(size_t box_capacity) {
    text_detector_result_t* result = (text_detector_result_t*)malloc(sizeof(text_detector_result_t));
    if (!result) {
        return NULL;
    }

    result->boxes.boxes = (text_detector_box_t*)malloc(sizeof(text_detector_box_t) * box_capacity);
    if (!result->boxes.boxes) {
        free(result);
        return NULL;
    }

    result->boxes.count = 0;
    result->boxes.capacity = box_capacity;

    return result;
}

void text_detector_result_free(text_detector_result_t* result) {
    if (result) {
        free(result->boxes.boxes);
        free(result);
    }
}

size_t text_detector_result_get_count(const text_detector_result_t* result) {
    return result ? result->boxes.count : 0;
}

const text_detector_box_t* text_detector_result_get_boxes(const text_detector_result_t* result) {
    return result ? result->boxes.boxes : NULL;
}

text_detector_boxes_t* text_detector_boxes_create(size_t capacity) {
    text_detector_boxes_t* boxes = (text_detector_boxes_t*)malloc(sizeof(text_detector_boxes_t));
    if (!boxes) {
        return NULL;
    }

    boxes->boxes = (text_detector_box_t*)malloc(sizeof(text_detector_box_t) * capacity);
    if (!boxes->boxes) {
        free(boxes);
        return NULL;
    }

    boxes->count = 0;
    boxes->capacity = capacity;
    return boxes;
}

void text_detector_boxes_free(text_detector_boxes_t* boxes) {
    if (boxes) {
        free(boxes->boxes);
        free(boxes);
    }
}

static void convert_to_bounding_box_list(const BoundingBoxList* src, text_detector_boxes_t* dst) {
    dst->count = (src->count < (int)dst->capacity) ? (size_t)src->count : dst->capacity;
    for (size_t i = 0; i < dst->count; i++) {
        dst->boxes[i].x = src->boxes[i].x;
        dst->boxes[i].y = src->boxes[i].y;
        dst->boxes[i].width = src->boxes[i].width;
        dst->boxes[i].height = src->boxes[i].height;
        dst->boxes[i].confidence = src->boxes[i].confidence;
        dst->boxes[i].pixel_count = src->boxes[i].pixel_count;
    }
}

static void convert_from_bounding_box_list(const text_detector_boxes_t* src, BoundingBoxList* dst) {
    dst->count = (int)((src->count < MAX_COMPONENTS) ? src->count : MAX_COMPONENTS);
    for (int i = 0; i < dst->count; i++) {
        dst->boxes[i].x = src->boxes[i].x;
        dst->boxes[i].y = src->boxes[i].y;
        dst->boxes[i].width = src->boxes[i].width;
        dst->boxes[i].height = src->boxes[i].height;
        dst->boxes[i].confidence = src->boxes[i].confidence;
        dst->boxes[i].pixel_count = src->boxes[i].pixel_count;
    }
}

int text_detector_extract_boxes(const float output[1][1][TEXT_DETECTOR_OUTPUT_HEIGHT][TEXT_DETECTOR_OUTPUT_WIDTH],
                                 text_detector_boxes_t* boxes) {
    if (!boxes || !output) {
        return -1;
    }

    BoundingBoxList internal_boxes;
    int result = extract_text_boxes(output, &internal_boxes);
    if (result < 0) {
        return -1;
    }

    convert_to_bounding_box_list(&internal_boxes, boxes);
    return (int)boxes->count;
}

int text_detector_detect(const float rgb[TEXT_DETECTOR_INPUT_HEIGHT][TEXT_DETECTOR_INPUT_WIDTH][3],
                         text_detector_result_t* result) {
    if (!initialized) {
        return -1;
    }

    if (!rgb || !result) {
        return -1;
    }

    /* Convert input format from [height][width][3] to [batch][channel][height][width] */
    float input[1][3][TEXT_DETECTOR_INPUT_HEIGHT][TEXT_DETECTOR_INPUT_WIDTH];
    for (int y = 0; y < TEXT_DETECTOR_INPUT_HEIGHT; y++) {
        for (int x = 0; x < TEXT_DETECTOR_INPUT_WIDTH; x++) {
            input[0][0][y][x] = rgb[y][x][0];  /* R */
            input[0][1][y][x] = rgb[y][x][1];  /* G */
            input[0][2][y][x] = rgb[y][x][2];  /* B */
        }
    }

    /* Run inference */
    entry(input, result->output);

    /* Extract boxes if result has a boxes array allocated */
    if (result->boxes.boxes) {
        int box_count = text_detector_extract_boxes(result->output, &result->boxes);
        if (box_count < 0) {
            return -1;
        }
    }

    return 0;
}

int text_detector_load_png(const char* filename,
                           float rgb[TEXT_DETECTOR_INPUT_HEIGHT][TEXT_DETECTOR_INPUT_WIDTH][3]) {
    return load_png(filename, rgb);
}

int text_detector_save_annotated(const char* filename, const char* original_image,
                                 const text_detector_boxes_t* boxes) {
    if (!boxes || !filename || !original_image) {
        return -1;
    }

    BoundingBoxList internal_boxes;
    convert_from_bounding_box_list(boxes, &internal_boxes);

    return save_annotated_image(filename, original_image, &internal_boxes);
}

void text_detector_convert_to_pixels(text_detector_result_t* result, int padding) {
    if (!result) {
        return;
    }

    BoundingBoxList internal_boxes;
    convert_from_bounding_box_list(&result->boxes, &internal_boxes);
    convert_to_pixel_coords(&internal_boxes, padding);
    convert_to_bounding_box_list(&internal_boxes, &result->boxes);
}

int text_detector_save_crops(const char* original_image,
                             const text_detector_boxes_t* boxes,
                             const char* output_prefix) {
    if (!boxes || !original_image || !output_prefix) {
        return -1;
    }

    BoundingBoxList internal_boxes;
    convert_from_bounding_box_list(boxes, &internal_boxes);

    extern int save_cropped_regions(const char* original_image, const BoundingBoxList* boxes,
                                    const char* output_prefix);
    return save_cropped_regions(original_image, &internal_boxes, output_prefix);
}

text_detector_text_boxes_t* text_detector_text_boxes_create(size_t capacity) {
    text_detector_text_boxes_t* boxes = (text_detector_text_boxes_t*)malloc(sizeof(text_detector_text_boxes_t));
    if (!boxes) {
        return NULL;
    }

    boxes->boxes = (text_detector_text_box_t*)calloc(capacity, sizeof(text_detector_text_box_t));
    if (!boxes->boxes) {
        free(boxes);
        return NULL;
    }

    boxes->count = 0;
    boxes->capacity = capacity;
    return boxes;
}

void text_detector_text_boxes_free(text_detector_text_boxes_t* boxes) {
    if (boxes) {
        /* Free all text strings */
        for (size_t i = 0; i < boxes->count; i++) {
            if (boxes->boxes[i].text) {
                free(boxes->boxes[i].text);
            }
        }
        free(boxes->boxes);
        free(boxes);
    }
}

/* Internal transcription function from ocr.c */
extern int ocr_transcribe(const char* original_image,
                          const text_detector_boxes_t* boxes,
                          text_detector_text_boxes_t* text_boxes);

int text_detector_detect_and_transcribe(const char* original_image,
                                        const float rgb[TEXT_DETECTOR_INPUT_HEIGHT][TEXT_DETECTOR_INPUT_WIDTH][3],
                                        text_detector_text_boxes_t* text_boxes,
                                        int padding) {
    if (!initialized || !text_boxes) {
        return -1;
    }

    /* Allocate and run detection */
    text_detector_result_t* result = text_detector_result_create(text_boxes->capacity);
    if (!result) {
        return -1;
    }

    if (text_detector_detect(rgb, result) != 0) {
        text_detector_result_free(result);
        return -1;
    }

    if (result->boxes.count == 0) {
        text_boxes->count = 0;
        text_detector_result_free(result);
        return 0;
    }

    /* Convert to pixel coordinates */
    text_detector_convert_to_pixels(result, padding);

    /* Transcribe */
    int ret = ocr_transcribe(original_image, &result->boxes, text_boxes);

    text_detector_result_free(result);
    return ret;
}
